- type: entity
  name: SLE deployable barrier
  id: ASDeployableBarrierSLE
  description: A deployable barrier. Swipe your ID card to lock/unlock it.
  parent: DeployableBarrier
  components:
  - type: Sprite
    sprite: _AS/Objects/Specific/Security/barrier.rsi
    layers:
    - state: idle
    - state: locked
      map: ["enum.LockVisualLayers.Lock"]
