- type: job
  id: NFDetective
  name: job-name-nf-detective
  description: job-description-nf-detective
  playTimeTracker: JobDetective
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 43200 # 12 hours
    - !type:RoleTimeRequirement # Aurora Song
      role: JobSecurityCadet
      time: 10800 # 3 hours
    - !type:RoleTimeRequirement # Aurora Song
      role: JobSecurityOfficer
      time: 10800 # 3 hours
#  alternateRequirementSets: # Aurora Song - Remove alt playtime reqs, you should be trained for this role as a Rookie.
#    longerPlaytimeLessSec:
#    - !type:OverallPlaytimeRequirement
#      time: 360000 # 100 hours
  startingGear: NFDetectiveGear
  icon: JobIconNFDetective
  supervisors: job-supervisors-bailiff
  weight: 110
  displayWeight: 20
  canBeAntag: false
  access:
  - Detective
  - Prisoner
  accessGroups:
  - GeneralNfsdAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: NFDetectiveGear
  equipment:
    pocket1: NFWeaponRevolverInspector
    pocket2: FlashlightNfsdLite
  storage:
    back:
    - Flash
    - NFSpeedLoaderPistol45Overpressure
    - NFSpeedLoaderPistol45Rubber
    - ForensicPad
    - ForensicScanner
    - FrontierUplinkCoin10
    - LogProbeCartridge
    - RubberStampDetective
    - ContrabandForensicsModule
  licenses:
  - LicenseContrabandHandling

- type: chameleonOutfit
  id: NFDetectiveChameleonOutfit
  job: NFDetective
  hasMindShield: true
  equipment:
    head: ClothingHeadHatFedoraBrown
    mask: ClothingMaskGasSecurity
    eyes: ASClothingEyesGlassesSLE
    neck: ClothingNeckNfsdBadgeDetective
    gloves: ClothingHandsGlovesForensic
    shoes: ASClothingShoesBootsSLEDarkBlueFilled
    belt: ASClothingBeltSLEFilled
    outerClothing: ClothingOuterCoatTrench

